### ISSUE TITLE
LineSegment intersection(with:) doesn't work

### ISSUE THREAD

**Issue by florentdouine** [toineheuvelmans/Metron#9] opened 2018-01-30 12:24 UTC
Hi,
It seems like there is an issue with the calcul used in intersection(with:) function.
If you try this small example, you won't find any intersect point whereas it actually exist
```swift
let lineA = LineSegment(a: CGPoint(x:187.5, y:108.873626373626), b: CGPoint(x:352.335164835165, y:108.873626373626))
let lineB = LineSegment(a: CGPoint(x:272.0, y:88.0), b: CGPoint(x:354.0, y:388.0))
let point = lineA.intersection(with: lineB) //return nil
```
![geogebra-export](https://user-images.githubusercontent.com/3594599/35566235-ebd06eca-05c0-11e8-864c-3eb5f0c2da82.png)

**Comment by toineheuvelmans** [comment] 2018-02-02 12:08
Hi @florentdouine , thanks for pointing this out. I have committed a fix which is available in release 1.0.2.
The issue was caused by a very small rounding error in one of the functions that are called under the hood of `intersection(with: )`. It already allowed for a rounding error smaller than 1e-14, but I moved this to 1e-12. I must stretch here that the intent of Metron is to be accurately enough for UI and animation-related tasks, not for super exact geometry (therefore I chose to extend the CoreGraphics types, instead of introducing high-precision alternatives).
Thanks again for pointing it out!

**Closed as completed by toineheuvelmans** 2018-02-02 12:08 UTC
